backend:
  - changed-files:
      - any-glob-to-any-file:
          - src/backend/**
frontend:
  - changed-files:
      - any-glob-to-any-file:
          - src/frontend/**
auto-merge:
  - changed-files:
      - any-glob-to-any-file:
          - src/backend/**
          - src/frontend/**
