name: Auto Merge
on:
  pull_request:
    types: [labeled, opened, synchronize, ready_for_review, reopened]
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/auto-merge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          commit-message: pull-request-title
